### ISSUE TITLE
 System.loadLibrary("ModelAssimpNative");

### ISSUE THREAD

**Issue by ankitsevakhr** [anandmuralidhar24/AssimpAndroid#2]
Process: com.anandmuralidhar.assimpandroid, PID: 30380
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.anandmuralidhar.assimpandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.anandmuralidhar.assimpandroid-1/lib/arm, /system/fake-libs, /data/app/com.anandmuralidhar.assimpandroid-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libModelAssimpNative.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                       at java.lang.System.loadLibrary(System.java:1530)
                                                       at com.anandmuralidhar.assimpandroid.AssimpActivity.<clinit>(AssimpActivity.java:88)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2635)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                       at android.os.Looper.loop(Looper.java:203)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6293)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by anandmuralidhar24** [comment]
your device probably does not meet the requirements specified in the project.

**Comment by ankitsevakhr** [comment]
Hello

I am working this project since 2 month but not compile perfect in my
device.
Please send me perfect example for android Device (Android Code Zip file
 format )
which device perfect for these example.


Thanks

**Comment by anandmuralidhar24** [comment]
As I clearly mentioned earlier, check if your device is compatible else it will not run. It is not possible to send "perfect" example if your device is incompatible.

**Comment by ankitsevakhr** [comment]
how can check it my device are perfect for this demo.
